language: java
jdk:
  - openjdk8
script: mvn package --batch-mode -P integration-test --file pom.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  - jdk: openjdk8
branches:
  only:
    - master
  
